title: Design Guide Test
description: Test for design guide
remote_theme: just-the-docs/just-the-docs

url: https://bradleywell.github.io/Design-Guide-Test

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
